spin_manifest_version = 2

[application]
authors = ["Matt Butcher <matt.butcher@fermyon.com>"]
description = "Use KV store and JSON with Python"
name = "kv-json-example"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "kv-json-example"

[component.kv-json-example]
source = "app.wasm"
# IMPORTANT: Enable default KV store
key_value_stores = ["default"]
[component.kv-json-example.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py", "Pipfile"]
